# Generated by Django 2.1.5 on 2019-01-14 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('grupo_amigo', models.CharField(choices=[('E', 'Escola'), ('P', 'Prédio')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('etiqueta', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Coleções',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao', models.DateField()),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Amigo')),
            ],
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edicao', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Caixa')),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Colecao')),
            ],
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Revista'),
        ),
        migrations.AddField(
            model_name='amigo',
            name='revistas',
            field=models.ManyToManyField(through='core.Emprestimo', to='core.Revista'),
        ),
    ]
